In [ ]:
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
data = pd.read_csv(file_name)

Saving train.csv to train (1).csv

In [ ]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
print("First 5 rows of the dataset:")
print(data.head())

First 5 rows of the dataset:
    Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No
1  LP001003   Male     Yes          1      Graduate            No
2  LP001005   Male     Yes          0      Graduate           Yes
3  LP001006   Male     Yes          0  Not Graduate            No
4  LP001008   Male      No          0      Graduate            No

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0
1             4583             1508.0       128.0             360.0
2             3000                0.0        66.0             360.0
3             2583             2358.0       120.0             360.0
4             6000                0.0       141.0             360.0

   Credit_History Property_Area Loan_Status
0             1.0         Urban           Y
1             1.0         Rural           N
2             1.0         Urban           Y
3             1.0         Urban           Y
4             1.0         Urban           Y

In [ ]:
print("\nDataset Info:")
print(data.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB
None

In [ ]:
print("\nSummary Statistics:")
print(data.describe())

Summary Statistics:
       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000
mean       5403.459283        1621.245798  146.412162         342.00000
std        6109.041673        2926.248369   85.587325          65.12041
min         150.000000           0.000000    9.000000          12.00000
25%        2877.500000           0.000000  100.000000         360.00000
50%        3812.500000        1188.500000  128.000000         360.00000
75%        5795.000000        2297.250000  168.000000         360.00000
max       81000.000000       41667.000000  700.000000         480.00000

       Credit_History
count      564.000000
mean         0.842199
std          0.364878
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000

In [ ]:
print("\nMissing Values in Each Column:")
print(data.isnull().sum())

Missing Values in Each Column:
Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
print("\nColumn Names:")
print(data.columns)

Column Names:
Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
print("\nShape of the Dataset (Rows, Columns):")
print(data.shape)

Shape of the Dataset (Rows, Columns):
(614, 13)

In [ ]:
duplicate_rows = data.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_rows}")

Number of duplicate rows: 0

In [ ]:
categorical_cols = data.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"\nUnique values in column '{col}':")
    print(data[col].unique())

Unique values in column 'Loan_ID':
['LP001002' 'LP001003' 'LP001005' 'LP001006' 'LP001008' 'LP001011'
 'LP001013' 'LP001014' 'LP001018' 'LP001020' 'LP001024' 'LP001027'
 'LP001028' 'LP001029' 'LP001030' 'LP001032' 'LP001034' 'LP001036'
 'LP001038' 'LP001041' 'LP001043' 'LP001046' 'LP001047' 'LP001050'
 'LP001052' 'LP001066' 'LP001068' 'LP001073' 'LP001086' 'LP001087'
 'LP001091' 'LP001095' 'LP001097' 'LP001098' 'LP001100' 'LP001106'
 'LP001109' 'LP001112' 'LP001114' 'LP001116' 'LP001119' 'LP001120'
 'LP001123' 'LP001131' 'LP001136' 'LP001137' 'LP001138' 'LP001144'
 'LP001146' 'LP001151' 'LP001155' 'LP001157' 'LP001164' 'LP001179'
 'LP001186' 'LP001194' 'LP001195' 'LP001197' 'LP001198' 'LP001199'
 'LP001205' 'LP001206' 'LP001207' 'LP001213' 'LP001222' 'LP001225'
 'LP001228' 'LP001233' 'LP001238' 'LP001241' 'LP001243' 'LP001245'
 'LP001248' 'LP001250' 'LP001253' 'LP001255' 'LP001256' 'LP001259'
 'LP001263' 'LP001264' 'LP001265' 'LP001266' 'LP001267' 'LP001273'
 'LP001275' 'LP001279' 'LP001280' 'LP001282' 'LP001289' 'LP001310'
 'LP001316' 'LP001318' 'LP001319' 'LP001322' 'LP001325' 'LP001326'
 'LP001327' 'LP001333' 'LP001334' 'LP001343' 'LP001345' 'LP001349'
 'LP001350' 'LP001356' 'LP001357' 'LP001367' 'LP001369' 'LP001370'
 'LP001379' 'LP001384' 'LP001385' 'LP001387' 'LP001391' 'LP001392'
 'LP001398' 'LP001401' 'LP001404' 'LP001405' 'LP001421' 'LP001422'
 'LP001426' 'LP001430' 'LP001431' 'LP001432' 'LP001439' 'LP001443'
 'LP001448' 'LP001449' 'LP001451' 'LP001465' 'LP001469' 'LP001473'
 'LP001478' 'LP001482' 'LP001487' 'LP001488' 'LP001489' 'LP001491'
 'LP001492' 'LP001493' 'LP001497' 'LP001498' 'LP001504' 'LP001507'
 'LP001508' 'LP001514' 'LP001516' 'LP001518' 'LP001519' 'LP001520'
 'LP001528' 'LP001529' 'LP001531' 'LP001532' 'LP001535' 'LP001536'
 'LP001541' 'LP001543' 'LP001546' 'LP001552' 'LP001560' 'LP001562'
 'LP001565' 'LP001570' 'LP001572' 'LP001574' 'LP001577' 'LP001578'
 'LP001579' 'LP001580' 'LP001581' 'LP001585' 'LP001586' 'LP001594'
 'LP001603' 'LP001606' 'LP001608' 'LP001610' 'LP001616' 'LP001630'
 'LP001633' 'LP001634' 'LP001636' 'LP001637' 'LP001639' 'LP001640'
 'LP001641' 'LP001643' 'LP001644' 'LP001647' 'LP001653' 'LP001656'
 'LP001657' 'LP001658' 'LP001664' 'LP001665' 'LP001666' 'LP001669'
 'LP001671' 'LP001673' 'LP001674' 'LP001677' 'LP001682' 'LP001688'
 'LP001691' 'LP001692' 'LP001693' 'LP001698' 'LP001699' 'LP001702'
 'LP001708' 'LP001711' 'LP001713' 'LP001715' 'LP001716' 'LP001720'
 'LP001722' 'LP001726' 'LP001732' 'LP001734' 'LP001736' 'LP001743'
 'LP001744' 'LP001749' 'LP001750' 'LP001751' 'LP001754' 'LP001758'
 'LP001760' 'LP001761' 'LP001765' 'LP001768' 'LP001770' 'LP001776'
 'LP001778' 'LP001784' 'LP001786' 'LP001788' 'LP001790' 'LP001792'
 'LP001798' 'LP001800' 'LP001806' 'LP001807' 'LP001811' 'LP001813'
 'LP001814' 'LP001819' 'LP001824' 'LP001825' 'LP001835' 'LP001836'
 'LP001841' 'LP001843' 'LP001844' 'LP001846' 'LP001849' 'LP001854'
 'LP001859' 'LP001864' 'LP001865' 'LP001868' 'LP001870' 'LP001871'
 'LP001872' 'LP001875' 'LP001877' 'LP001882' 'LP001883' 'LP001884'
 'LP001888' 'LP001891' 'LP001892' 'LP001894' 'LP001896' 'LP001900'
 'LP001903' 'LP001904' 'LP001907' 'LP001908' 'LP001910' 'LP001914'
 'LP001915' 'LP001917' 'LP001922' 'LP001924' 'LP001925' 'LP001926'
 'LP001931' 'LP001935' 'LP001936' 'LP001938' 'LP001940' 'LP001945'
 'LP001947' 'LP001949' 'LP001953' 'LP001954' 'LP001955' 'LP001963'
 'LP001964' 'LP001972' 'LP001974' 'LP001977' 'LP001978' 'LP001990'
 'LP001993' 'LP001994' 'LP001996' 'LP001998' 'LP002002' 'LP002004'
 'LP002006' 'LP002008' 'LP002024' 'LP002031' 'LP002035' 'LP002036'
 'LP002043' 'LP002050' 'LP002051' 'LP002053' 'LP002054' 'LP002055'
 'LP002065' 'LP002067' 'LP002068' 'LP002082' 'LP002086' 'LP002087'
 'LP002097' 'LP002098' 'LP002100' 'LP002101' 'LP002103' 'LP002106'
 'LP002110' 'LP002112' 'LP002113' 'LP002114' 'LP002115' 'LP002116'
 'LP002119' 'LP002126' 'LP002128' 'LP002129' 'LP002130' 'LP002131'
 'LP002137' 'LP002138' 'LP002139' 'LP002140' 'LP002141' 'LP002142'
 'LP002143' 'LP002144' 'LP002149' 'LP002151' 'LP002158' 'LP002160'
 'LP002161' 'LP002170' 'LP002175' 'LP002178' 'LP002180' 'LP002181'
 'LP002187' 'LP002188' 'LP002190' 'LP002191' 'LP002194' 'LP002197'
 'LP002201' 'LP002205' 'LP002209' 'LP002211' 'LP002219' 'LP002223'
 'LP002224' 'LP002225' 'LP002226' 'LP002229' 'LP002231' 'LP002234'
 'LP002236' 'LP002237' 'LP002239' 'LP002243' 'LP002244' 'LP002250'
 'LP002255' 'LP002262' 'LP002263' 'LP002265' 'LP002266' 'LP002272'
 'LP002277' 'LP002281' 'LP002284' 'LP002287' 'LP002288' 'LP002296'
 'LP002297' 'LP002300' 'LP002301' 'LP002305' 'LP002308' 'LP002314'
 'LP002315' 'LP002317' 'LP002318' 'LP002319' 'LP002328' 'LP002332'
 'LP002335' 'LP002337' 'LP002341' 'LP002342' 'LP002345' 'LP002347'
 'LP002348' 'LP002357' 'LP002361' 'LP002362' 'LP002364' 'LP002366'
 'LP002367' 'LP002368' 'LP002369' 'LP002370' 'LP002377' 'LP002379'
 'LP002386' 'LP002387' 'LP002390' 'LP002393' 'LP002398' 'LP002401'
 'LP002403' 'LP002407' 'LP002408' 'LP002409' 'LP002418' 'LP002422'
 'LP002424' 'LP002429' 'LP002434' 'LP002435' 'LP002443' 'LP002444'
 'LP002446' 'LP002447' 'LP002448' 'LP002449' 'LP002453' 'LP002455'
 'LP002459' 'LP002467' 'LP002472' 'LP002473' 'LP002478' 'LP002484'
 'LP002487' 'LP002489' 'LP002493' 'LP002494' 'LP002500' 'LP002501'
 'LP002502' 'LP002505' 'LP002515' 'LP002517' 'LP002519' 'LP002522'
 'LP002524' 'LP002527' 'LP002529' 'LP002530' 'LP002531' 'LP002533'
 'LP002534' 'LP002536' 'LP002537' 'LP002541' 'LP002543' 'LP002544'
 'LP002545' 'LP002547' 'LP002555' 'LP002556' 'LP002560' 'LP002562'
 'LP002571' 'LP002582' 'LP002585' 'LP002586' 'LP002587' 'LP002588'
 'LP002600' 'LP002602' 'LP002603' 'LP002606' 'LP002615' 'LP002618'
 'LP002619' 'LP002622' 'LP002624' 'LP002625' 'LP002626' 'LP002634'
 'LP002637' 'LP002640' 'LP002643' 'LP002648' 'LP002652' 'LP002659'
 'LP002670' 'LP002682' 'LP002683' 'LP002684' 'LP002689' 'LP002690'
 'LP002692' 'LP002693' 'LP002697' 'LP002699' 'LP002705' 'LP002706'
 'LP002714' 'LP002716' 'LP002717' 'LP002720' 'LP002723' 'LP002729'
 'LP002731' 'LP002732' 'LP002734' 'LP002738' 'LP002739' 'LP002740'
 'LP002741' 'LP002743' 'LP002753' 'LP002755' 'LP002757' 'LP002767'
 'LP002768' 'LP002772' 'LP002776' 'LP002777' 'LP002778' 'LP002784'
 'LP002785' 'LP002788' 'LP002789' 'LP002792' 'LP002794' 'LP002795'
 'LP002798' 'LP002804' 'LP002807' 'LP002813' 'LP002820' 'LP002821'
 'LP002832' 'LP002833' 'LP002836' 'LP002837' 'LP002840' 'LP002841'
 'LP002842' 'LP002847' 'LP002855' 'LP002862' 'LP002863' 'LP002868'
 'LP002872' 'LP002874' 'LP002877' 'LP002888' 'LP002892' 'LP002893'
 'LP002894' 'LP002898' 'LP002911' 'LP002912' 'LP002916' 'LP002917'
 'LP002925' 'LP002926' 'LP002928' 'LP002931' 'LP002933' 'LP002936'
 'LP002938' 'LP002940' 'LP002941' 'LP002943' 'LP002945' 'LP002948'
 'LP002949' 'LP002950' 'LP002953' 'LP002958' 'LP002959' 'LP002960'
 'LP002961' 'LP002964' 'LP002974' 'LP002978' 'LP002979' 'LP002983'
 'LP002984' 'LP002990']

Unique values in column 'Gender':
['Male' 'Female' nan]

Unique values in column 'Married':
['No' 'Yes' nan]

Unique values in column 'Dependents':
['0' '1' '2' '3+' nan]

Unique values in column 'Education':
['Graduate' 'Not Graduate']

Unique values in column 'Self_Employed':
['No' 'Yes' nan]

Unique values in column 'Property_Area':
['Urban' 'Rural' 'Semiurban']

Unique values in column 'Loan_Status':
['Y' 'N']

In [ ]:
if not data.select_dtypes(include=[np.number]).empty:
    print("\nCorrelation Matrix (Numerical Columns):")
    numerical_data = data.select_dtypes(include=[np.number])
    print(numerical_data.corr())

Correlation Matrix (Numerical Columns):
                   ApplicantIncome  CoapplicantIncome  LoanAmount  \
ApplicantIncome           1.000000          -0.116605    0.570909
CoapplicantIncome        -0.116605           1.000000    0.188619
LoanAmount                0.570909           0.188619    1.000000
Loan_Amount_Term         -0.045306          -0.059878    0.039447
Credit_History           -0.014715          -0.002056   -0.008433

                   Loan_Amount_Term  Credit_History
ApplicantIncome           -0.045306       -0.014715
CoapplicantIncome         -0.059878       -0.002056
LoanAmount                 0.039447       -0.008433
Loan_Amount_Term           1.000000        0.001470
Credit_History             0.001470        1.000000